SCREEN_WIDTH = 600
SCREEN_HEIGHT = 400
PLAY_WIDTH = 25
PLAY_HEIGHT = 25
PLAYER_START = [SCREEN_WIDTH/2, SCREEN_HEIGHT/2]
PLAYER_SPEED = 3

# SCALE_FACTOR = 0.11
SCALE_FACTOR = 1

SCREEN_WIDTH_SCALED = SCREEN_WIDTH // SCALE_FACTOR
SCREEN_HEIGHT_SCALED = SCREEN_HEIGHT // SCALE_FACTOR

FOOD_START = 11000

PLANT_NR = 5
HUNTER_NR = 5

PLANT_OBSERVATIONS = 10
HUNTER_OBSERVATIONS = 6

TARGET_INTERVAL = 30000
CYCLE_INTERVAL = 200
